"""add in_unit_laundry, income restriction, photos_used columns

Revision ID: 19fa450457d8
Revises: bb2f4a9e7ed7
Create Date: 2026-06-03 06:57:50.268773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19fa450457d8'
down_revision: Union[str, Sequence[str], None] = 'bb2f4a9e7ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('enrichments', sa.Column('in_unit_laundry', sa.Boolean(), nullable=True))
    op.add_column('enrichments', sa.Column('income_restricted', sa.Boolean(), nullable=True))
    op.add_column('enrichments', sa.Column('income_restriction_details', sa.Text(), nullable=True))
    op.add_column('enrichments', sa.Column('photos_used', sa.Integer(), nullable=True))
    op.add_column('listings', sa.Column('in_unit_laundry', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listings', 'in_unit_laundry')
    op.drop_column('enrichments', 'photos_used')
    op.drop_column('enrichments', 'income_restriction_details')
    op.drop_column('enrichments', 'income_restricted')
    op.drop_column('enrichments', 'in_unit_laundry')
    # ### end Alembic commands ###
