"""initial schema: listings, price_history, enrichments

Revision ID: bb2f4a9e7ed7
Revises: 
Create Date: 2026-06-02 20:19:16.999707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bb2f4a9e7ed7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('listing_id', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('zpid', sa.String(length=32), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('state', sa.String(length=16), nullable=True),
    sa.Column('zipcode', sa.String(length=16), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('rent', sa.Integer(), nullable=True),
    sa.Column('beds', sa.Float(), nullable=True),
    sa.Column('baths', sa.Float(), nullable=True),
    sa.Column('sqft', sa.Integer(), nullable=True),
    sa.Column('building_name', sa.Text(), nullable=True),
    sa.Column('unit_number', sa.String(length=32), nullable=True),
    sa.Column('available_from', sa.Date(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('orientation', sa.String(length=16), nullable=True),
    sa.Column('parking_fee', sa.Integer(), nullable=True),
    sa.Column('pet_rent', sa.Integer(), nullable=True),
    sa.Column('application_fee', sa.Integer(), nullable=True),
    sa.Column('deposit', sa.Integer(), nullable=True),
    sa.Column('utilities_included', sa.Boolean(), nullable=True),
    sa.Column('walk_score', sa.Integer(), nullable=True),
    sa.Column('transit_score', sa.Integer(), nullable=True),
    sa.Column('bike_score', sa.Integer(), nullable=True),
    sa.Column('amenities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('score_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_index(op.f('ix_listings_is_active'), 'listings', ['is_active'], unique=False)
    op.create_index(op.f('ix_listings_rent'), 'listings', ['rent'], unique=False)
    op.create_index(op.f('ix_listings_score'), 'listings', ['score'], unique=False)
    op.create_index(op.f('ix_listings_source'), 'listings', ['source'], unique=False)
    op.create_index(op.f('ix_listings_zipcode'), 'listings', ['zipcode'], unique=False)
    op.create_table('enrichments',
    sa.Column('listing_id', sa.String(length=128), nullable=False),
    sa.Column('deals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('concessions', sa.Text(), nullable=True),
    sa.Column('community_events', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('vibe_summary', sa.Text(), nullable=True),
    sa.Column('inferred_floor', sa.Integer(), nullable=True),
    sa.Column('inferred_orientation', sa.String(length=16), nullable=True),
    sa.Column('model_used', sa.String(length=80), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.listing_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('listing_id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('listing_id', sa.String(length=128), nullable=False),
    sa.Column('rent', sa.Integer(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.listing_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_listing_id'), 'price_history', ['listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_price_history_listing_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_table('enrichments')
    op.drop_index(op.f('ix_listings_zipcode'), table_name='listings')
    op.drop_index(op.f('ix_listings_source'), table_name='listings')
    op.drop_index(op.f('ix_listings_score'), table_name='listings')
    op.drop_index(op.f('ix_listings_rent'), table_name='listings')
    op.drop_index(op.f('ix_listings_is_active'), table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
